version: '3'

services:
  medical-clinic:
    image: medical-clinic:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medical-clinic
    networks:
      - med-network

  medical-clinic-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      MEDICAL_CLINIC_URL: http://medical-clinic:8080
#      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_MEDICAL_MEDICAL-CLINIC_URL: http://medical-clinic:8080
    depends_on:
      - medical-clinic
    networks:
      - med-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: medical-clinic
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - med-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - med-network

volumes:
  postgres_data:

networks:
  med-network:
    driver: bridge