version: '3'

services:
  medical-clinic:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - med-network

  medical-clinic-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - medical-clinic
    networks:
      - med-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: medical-clinic
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - med-network

volumes:
  postgres_data:
networks:
  med-network:
    driver: bridge